#!/bin/bash
spacesPerTab=0

if [ "$1" = "-h" ]
then
	echo <<EOF
	Retab changes spaces to tabs because some people think spaces are acceptable.

	usage : retab FILENAME [NEWFILE]

	filename will be modified in place unless newfile is provided
EOF
exit 0
fi

{
while IFS= read -r line 
	do
		# Debug echo "$line"
		numSpaces="$(echo "$line" | sed -e 's?\( *\).*$?\1?' | awk '{ print length }')"
		# debug echo $numSpaces
		if [ "$spacesPerTab" == "0" ]
		then
			if [ "$numSpaces" != "0" ]
				then
				spacesPerTab=$numSpaces
			else
				echo "$line"
				continue;
			fi
		fi

		if [ "$numSpaces" == "0" ] #if there's no spaces, we give up
			then 
			echo "$line"
			continue
		fi

		(( numtabs = numSpaces/spacesPerTab ))
	 
		insertTabs=$'\t'

		for (( i = 1; i < numTabs; i++ ))
		do
			insertTabs=$insertTabs"$"'\t'
		done

		echo "$line" | sed 's? *?'"$insertTabs"'?' 


done < "$1"
} > "/tmp/retab.tmp"

if [[ "$2" -eq $NULL ]]
	then
	mv "/tmp/retab.tmp" "$1"
else
	mv "/tmp/retab.tmp" "$2"
fi

