#!/bin/bash


spacesPerTab=0

{
	while IFS= read -r line 
	do
		echo "$line"
		numSpaces="$(echo "$line" | sed -e 's?\( *\).*$?\1?' | awk '{ print length }')"
		echo $numSpaces
		if [ "$spacesPerTab" == "0" ]
		then
			if [ "$numSpaces" != "0" ]
				then
				spacesPerTab=$numSpaces
			else
				echo "$line"
				continue;
			fi
		fi

		if [ "$numSpaces" == "0" ] #if there's no spaces, we give up
			then continue
		fi

		(( numtabs = numSpaces/spacesPerTab ))
	 
		insertTabs=$'\t'

		for (( i = 1; i < numTabs; i++ ))
		do
			insertTabs=$insertTabs"$"'\t'
		done

		echo "$line" | sed 's? *?'"$insertTabs"'?' >


	done < "$1"
} > "$2"