#!/bin/bash


spacesPerTab=0

while IFS= read -r line 
	numSpaces = echo $line | sed -e 's?\( *\).*$?\1?' | awk '{ print length }'
	if [ $spacesPerTab -eq 0 ]
	then
		if [ $numSpaces -ne 0 ]
			then
			spacesPerTab=$numSpaces
		else
			continue;
		fi
	fi

	if [ numSpaces -eq 0 ] #if there's no spaces, we give up
		then continue
	fi

	numTabs=(( numSpaces/spacesPerTab ))
 
	insertTabs=$'\t'

	for (( i = 1; i < numTabs; i++ ))
	do
		insertTabs=$insertTabs"$"'\t'
	done

	sed -i 's? *?'"$insertTabs"'?' 


done < cat $1 